- name: create user
  user: name="{{ user_name }}" password="{{ user_pass }}" shell=/bin/bash groups="{{ user_groups }}"

- name: create sudoer file
  copy: content="{{ user_name }} ALL=(ALL) NOPASSWD:ALL"
        dest="/etc/sudoers.d/{{ user_name }}"
        owner=root
        group=root
        mode=0440

#- name: add SSH authorized key
#  authorized_key: user="{{ user_name }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
