- name: create user
  user: name="{{ user }}" shell=/bin/bash

- name: create sudoer file
  copy: content="{{ user }} ALL=(ALL) NOPASSWD:ALL"
        dest="/etc/sudoers.d/{{ user }}"
        owner=root
        group=root
        mode=0440

#- name: add SSH authorized key
#  authorized_key: user="{{ user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
