
---
create_swap_file: no
swap_file_path: /swapfile
swap_file_size_kb: 512

update_apt_cache: no

user_name: wiki_club_user
user_pass: "pass"
user_groups: www-data

home_path: "/home/{{ user_name }}"

project_name: wiki_allatra_club
project_path: "{{ home_path }}/{{ project_name }}"
project_repo_path: "{{ home_path }}/{{ project_name }}_repo.git"
virtualenv_path: "{{ home_path }}/virtualenv"

http_port: 80
domain: wiki.allatra.club
git_source: https://Infernion@bitbucket.org/Infernion/wiki_allatra_club.git

db_name: "{{ project_name }}_db"
db_user: "{{ user_name }}"
db_password: "pass"


# Application settings.
application_name: "{{ project_name }}"
application_log_dir: "{{ project_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
gunicorn_user: "{{ user_name }}"
gunicorn_group: "{{ user_groups }}"
gunicorn_num_workers: 3
gunicorn_max_requests: 0


# Nginx settings
nginx_server_name: "wiki.allatra.club www.wiki.allatra.club"
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/staticfiles/"
nginx_media_dir: "{{ project_path }}/{{ application_name }}/media/"

# Django Environment variables
django_secret_key: "key"
django_settings_file: "{{ project_path }}/config/settings/local.py"

django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
